apiVersion: apps/v1
kind: Deployment
metadata:
  name: maven-sample
spec:
  replicas: 2
  selector:
    matchLabels:
      app: maven-sample
  template:
    metadata:
      labels:
        app: maven-sample
    spec:
      containers:
        - name: maven-sample
          image: muralikrishnavaitla/maven-sample-project:latest
          ports:
            - containerPort: 8080
          env:
            - name: JAVA_OPTS
              value: "-Xmx512m"
---------
apiVersion: v1
kind: Service
metadata:
  name: maven-sample
spec:
  selector:
    app: maven-sample
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
